# Generated by Django 4.1.2 on 2022-10-31 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
