# Generated by Django 4.1.2 on 2022-10-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
